-- Drop all tables and enums
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS listings CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS alembic_version CASCADE;

-- Drop enums
DROP TYPE IF EXISTS userrole CASCADE;
DROP TYPE IF EXISTS userstatus CASCADE;
DROP TYPE IF EXISTS plantype CASCADE;
DROP TYPE IF EXISTS subscriptionstatus CASCADE;
DROP TYPE IF EXISTS paymentstatus CASCADE;
DROP TYPE IF EXISTS listingstatus CASCADE;
DROP TYPE IF EXISTS contactmessagetype CASCADE;
DROP TYPE IF EXISTS contactmessagestatus CASCADE;
